### ISSUE TITLE
I would like to suggest that we move the ALB to a new module.

### ISSUE THREAD

**Issue by qvistgaard** [nuuday/terraform-aws-eks#8]
We could have cases where people want to do something else, it would make it easier give a better overview if it moved to a different module

**Comment by anarsen** [comment]
Sure. I thought of calling it `terraform-aws-eks-ingress` back when. 

Generally though, I'd prefer to change only what we _know_ needs changing. I could see the case if you didn't want public ingress, but then you'd just set `ingress_enable = false`.

Oh, and it's not an ALB as the issue title indicates. It's an NLB we provision.

**Comment by anarsen** [comment]
cc @wolffberg

**Comment by anarsen** [comment]
As discussed in #9 we're going to move the NLB out and use the official `terraform-aws-alb` module directly.

You can close this @qvistgaard if you agree.
