### ISSUE TITLE
design: modular approach - what should it look like?

### ISSUE THREAD

**Issue by anarsen** [nuuday/terraform-aws-eks#9]
# Context

As a [sample](https://github.com/nuuday/sitecore-aws-environment-samples/tree/master/k8s), the simple variables such as `linux_workers_count` sufficed. In a real-life scenario you'd want much more control over the ASGs and launch templates yourself, as @ssoerensen also points out in #3 #4 and #8.

While you're at it, you'd probably want access to the variables for the inner `aws_eks_cluster` resource itself too.

It's starting to look like the initial value proposition of this `terraform-aws-eks` module isn't as good. There are still a lot of good parts, namely

- Ingress (LB and ingress controller)
- External DNS
- Cert Manager
- Spot Instance Termination Handler
- Cluster Autoscaler
- Metrics Server

# Proposal

We provide Terraform modules for each of these good parts, and make it up to the consumers of them to provision the EKS cluster themselves - perhaps through the official `terraform-aws-eks` module.

Consumers would have Terraform outlined as

```terraform
module "cluster" {
  source = "github.com/terraform-aws-modules/terraform-aws-eks"
  # ..
}

module "lb" {
  source = "github.com/terraform-aws-modules/terraform-aws-alb"
  # ..
}

module "ingress" {
  source = "github.com/nuuday/terraform-aws-eks-ingress"

  cluster_arn = module.cluster.this_cluster_arn
  lb_fqdn = module.lb.this_lb_dns_name
  # ..
}

module "addons" {
  source = "github.com/nuuday/terraform-aws-eks-addons"

  cluster_arn = module.cluster.this_cluster_arn

  # Addons we'd consider must-haves could be 'true' by default
  cluster_autoscaler_enable = true
}
```

Feedback, please :heart:

**Comment by anarsen** [comment]
@ssoerensen @wolffberg I decided to take the modular design discussion into a separate issue. Let's continue discussing it here.

What do you think of the proposal in the OP?

**Comment by wolffberg** [comment]
If we decide to split it up, I would definately go with the last option and have a module with all the addons.

**Comment by anarsen** [comment]
Also, we could decide to bundle the NLB and ingress controller in an _ingress_ module.

**Comment by anarsen** [comment]
> If we decide to split it up, I would definately go with the last option and have a module with all the addons.

Just to be sure - my proposal was actually that the Terraform would look like that - it's one option so to say.

Is your point to have it look like this @wolffberg? If yes, then I'm onboard :tada:  

```terraform
module "cluster" {
  source = "github.com/terraform-aws-modules/terraform-aws-eks"

  # a thousand attributes are set here
}


module "addons" {
  source = "github.com/nuuday/terraform-aws-eks-addons"

  cluster_arn = module.cluster.this_cluster_arn

  # Addons we'd consider must-haves could be 'true' by default
  cluster_autoscaler_enable = true
  ingress_enable = true # NLB and ingress controller

  # ..
}
```

**Comment by micka1** [comment]
Have you look at our https://github.com/nuuday/managed-kubernetes-cluster repo design from the mob session ?

**Comment by anarsen** [comment]
@micka1 I have now :+1: 

@ssoerensen has different needs for which variables to expose than what the sample provided, and we're trying to come up with a more DRY-way of sizing the modules.

That said, it would be nice to re-use as much as possible from the modules you and I already made, but for now I think it's more important to discuss the boundaries of the modules. Newest proposal is here: https://github.com/nuuday/terraform-aws-eks/issues/9#issuecomment-635162126

**Comment by anarsen** [comment]
We did a short call on this. We agreed that **this** repository will contain a wrapper surrounding `terraform-aws-modules/terraform-aws-eks` and kept API compatible.

The reason behind doing that is to provide defaults for e.g. security groups. @ssoerensen is in charge of that.

In addition to this repository, we will break the add-ons out and put them in [nuuday/terraform-aws-eks-addons](https://github.com/nuuday/terraform-aws-eks-addons). We in Shared Platforms are in charge of this.

The folder structure inside `nuuday/terraform-aws-eks-addons` will look like this

```
/modules
  cert-manager/
    - main.tf
    - variables.tf
  external-dns/
    - main.tf
    - variables.tf
main.tf
variables.tf
```

This way it'll be possible to reference individual add-ons instead of the whole package if needed.

**Comment by qvistgaard** [comment]
It would be easier to maintain the lint and fmt pipelines if everything is on the same folder:
```
/addon-cert-manager
   main.tf
   ....
/addon-external-dns
/addon-all (or something like that)
```
it will make the process of keeping workflows up to date a lot easier

**Comment by anarsen** [comment]
`terraform fmt -recursive -check` and iterating over all folders inside `addons/` would do the trick.

If we keep it in a flat structure, i.e. **one** module, it will not be possible to reference individual add-on modules if you want to do that.

**Comment by qvistgaard** [comment]
Ok, No problems then
